version: '3'

services:
  postgres:
    container_name: 'app_db'
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./dumps:/app/dumps
      - ./data/app_db:/var/lib/app_db/data
